CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMIN','AGENT') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    CONSTRAINT fk_agent_user FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    agent_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    nationality VARCHAR(255),
    poste VARCHAR(255) NOT NULL,
    club VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    access_code INT NOT NULL UNIQUE,
    CONSTRAINT fk_player_agent FOREIGN KEY (agent_id) REFERENCES agent(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agenda (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    owner_type ENUM('AGENT','PLAYER') NOT NULL,
    owner_id INT NOT NULL,
    color VARCHAR(7) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    agenda_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    date_heure_debut DATETIME NOT NULL,
    date_heure_fin DATETIME NOT NULL,
    type VARCHAR(255) NOT NULL,
    CONSTRAINT fk_event_agenda FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS statistique (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    player_id INT NOT NULL,
    saison VARCHAR(50) NOT NULL,
    matchs_joues INT DEFAULT 0,
    buts INT DEFAULT 0,
    passes_decisives INT DEFAULT 0,
    taille DECIMAL(3,2) NOT NULL,
    poids DECIMAL(5,2) NOT NULL,
    cartons_jaunes INT DEFAULT 0,
    cartons_rouges INT DEFAULT 0,
    CONSTRAINT fk_statistique_player FOREIGN KEY (player_id) REFERENCES player(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
